# Generated by Django 5.2.5 on 2025-09-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='priority',
            field=models.CharField(choices=[('higher', 'Higher'), ('medium', 'Medium')], default='medium', help_text='if News set to higher priority, will always be displayed in page', max_length=20),
        ),
    ]
